% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Tarea 1 - Martín Olivera - CI. 4845488-3},
  pdfauthor={STAT\_NT},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Tarea 1 - Martín Olivera - CI. 4845488-3}
\author{STAT\_NT}
\date{7/5/2021}

\begin{document}
\maketitle

\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\E}{\bs{\mathcal{E}}}
\newcommand{\F}{\bs{\mathcal{F}}}
\renewcommand{\v}{\bs{v}}
\renewcommand{\bfdefault}{m}

\hypertarget{ejercicio-1}{%
\section{Ejercicio 1}\label{ejercicio-1}}

\hypertarget{parte-1-vectores}{%
\subsection{Parte 1: Vectores}\label{parte-1-vectores}}

\hypertarget{dado-los-siguientes-vectores-indicuxe1-a-quuxe9-tipo-de-vector-coercionan.}{%
\subsubsection{Dado los siguientes vectores, indicá a qué tipo de vector
coercionan.}\label{dado-los-siguientes-vectores-indicuxe1-a-quuxe9-tipo-de-vector-coercionan.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{w }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{29}\NormalTok{, 1L, }\ConstantTok{FALSE}\NormalTok{, }\StringTok{"HOLA"}\NormalTok{)}
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Celeste pelela!"}\NormalTok{, }\DecValTok{33}\NormalTok{, }\ConstantTok{NA}\NormalTok{)}
\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{25}\NormalTok{), 10L)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(}\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\SpecialCharTok{:}\DecValTok{25}\NormalTok{), 10L)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(w)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "character"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "character"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "integer"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{class}\NormalTok{(z)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "character"
\end{verbatim}

A partir de la función class (así como de la función str) se obtiene que
el vector w, x y z son vectores characters, mientras que el vector y es
integer. w, x contiene palabras, expresiones lógicas y números. y
contiene números mientras que z concatena la secuencia con el número 10.

\hypertarget{cuuxe1l-es-la-diferencia-entre-c4-3-2-1-y-41}{%
\subsubsection{\texorpdfstring{¿Cuál es la diferencia entre
\texttt{c(4,\ 3,\ 2,\ 1)} y
\texttt{4:1}?}{¿Cuál es la diferencia entre c(4, 3, 2, 1) y 4:1?}}\label{cuuxe1l-es-la-diferencia-entre-c4-3-2-1-y-41}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4 3 2 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{4}\SpecialCharTok{:}\DecValTok{1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4 3 2 1
\end{verbatim}

La diferencia que se observa entre ambas opciones es que aunque el
resultado final devuelve en ambos casos la secuencia de números de 4 a 1
decrecientes de a 1, c() devuelve la secuencia de carácter numéric,
mientras que la secuencia 4:1 devuelve la secuencia siendo integer.

\hypertarget{parte-2-factor}{%
\subsection{\texorpdfstring{Parte 2:
\texttt{factor}}{Parte 2: factor}}\label{parte-2-factor}}

Dado el siguiente \texttt{factor} \texttt{x}:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}}
   \FunctionTok{factor}\NormalTok{(}
      \FunctionTok{c}\NormalTok{(}
         \StringTok{"alto"}\NormalTok{,}
         \StringTok{"bajo"}\NormalTok{,}
         \StringTok{"medio"}\NormalTok{,}
         \StringTok{"alto"}\NormalTok{,}
         \StringTok{"muy alto"}\NormalTok{,}
         \StringTok{"bajo"}\NormalTok{,}
         \StringTok{"medio"}\NormalTok{,}
         \StringTok{"alto"}\NormalTok{,}
         \StringTok{"ALTO"}\NormalTok{,}
         \StringTok{"MEDIO"}\NormalTok{,}
         \StringTok{"BAJO"}\NormalTok{,}
         \StringTok{"MUY ALTO"}\NormalTok{,}
         \StringTok{"QUE LOCO"}\NormalTok{,}
         \StringTok{"QUE LOCO"}\NormalTok{,}
         \StringTok{"QUE LOCO"}\NormalTok{,}
         \StringTok{"A"}\NormalTok{,}
         \StringTok{"B"}\NormalTok{,}
         \StringTok{"C"}\NormalTok{,}
         \StringTok{"GUAU"}\NormalTok{,}
         \StringTok{"GOL"}\NormalTok{,}
         \StringTok{"MUY BAJO"}\NormalTok{,}
         \StringTok{"MUY BAJO"}\NormalTok{,}
         \StringTok{"MUY ALTO"}
\NormalTok{      )}
\NormalTok{   )}
\end{Highlighting}
\end{Shaded}

\hypertarget{generuxe1-un-nuevo-factor-llamalo-xx-transformando-el-objeto-x-previamente-generado-de-forma-que-quede-como-sigue}{%
\subsubsection{\texorpdfstring{Generá un nuevo \texttt{factor} (llamalo
\texttt{xx}) transformando el objeto \texttt{x} previamente generado de
forma que quede como
sigue:}{Generá un nuevo factor (llamalo xx) transformando el objeto x previamente generado de forma que quede como sigue:}}\label{generuxe1-un-nuevo-factor-llamalo-xx-transformando-el-objeto-x-previamente-generado-de-forma-que-quede-como-sigue}}

\texttt{xx}

\texttt{{[}1{]}\ A\ B\ M\ A\ A\ B\ M\ A\ A\ M\ B\ A\ B\ B\ A}

\texttt{Levels:\ B\ \textless{}\ M\ \textless{}\ A}

\textbf{Observación}:

\begin{itemize}
\tightlist
\item
  El largo es de 23.
\item
  Se deben corregir (y tomar en cuenta) todos los casos que contengan
  las palabras: bajo, medio, alto. Es decir, ``MUY ALTO'', ``ALTO''
  deben transformarse a ``alto'' y así sucesivamente.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] alto     bajo     medio    muy alto ALTO     MEDIO    BAJO     MUY ALTO
##  [9] QUE LOCO A        B        C        GUAU     GOL      MUY BAJO
## 15 Levels: A alto ALTO B bajo BAJO C GOL GUAU medio MEDIO muy alto ... QUE LOCO
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{aux}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(}\StringTok{"alto"}\NormalTok{, }\StringTok{"ALTO"}\NormalTok{,}\StringTok{"bajo"}\NormalTok{, }\StringTok{"BAJO"}\NormalTok{, }\StringTok{"medio"}\NormalTok{, }\StringTok{"MEDIO"}\NormalTok{,}\StringTok{"muy alto"}\NormalTok{,}\StringTok{"MUY ALTO"}\NormalTok{, }\StringTok{"MUY BAJO"}\NormalTok{)}
\NormalTok{xx}\OtherTok{\textless{}{-}}\NormalTok{x[}\FunctionTok{which}\NormalTok{(x}\SpecialCharTok{\%in\%}\NormalTok{aux)]}
\NormalTok{xx}\OtherTok{\textless{}{-}}\FunctionTok{factor}\NormalTok{(xx,}\AttributeTok{levels=}\NormalTok{aux)}
\NormalTok{xxx}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{()}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(xx))\{}
  \ControlFlowTok{if}\NormalTok{ (xx[i]}\SpecialCharTok{\%in\%}\FunctionTok{c}\NormalTok{(}\StringTok{"ALTO"}\NormalTok{,}\StringTok{"MUY ALTO"}\NormalTok{, }\StringTok{"muy alto"}\NormalTok{))\{}
\NormalTok{    xxx[i]}\OtherTok{=}\StringTok{"alto"}
\NormalTok{  \} }\ControlFlowTok{else} \ControlFlowTok{if}\NormalTok{ (xx[i]}\SpecialCharTok{\%in\%}\FunctionTok{c}\NormalTok{(}\StringTok{"BAJO"}\NormalTok{,}\StringTok{"MUY BAJO"}\NormalTok{))\{}
\NormalTok{    xxx[i]}\OtherTok{=}\StringTok{"bajo"}
\NormalTok{  \} }\ControlFlowTok{else} \ControlFlowTok{if}\NormalTok{ (xx[i]}\SpecialCharTok{==}\StringTok{"MEDIO"}\NormalTok{)\{}
\NormalTok{    xxx[i]}\OtherTok{=}\StringTok{"medio"}
\NormalTok{  \} }
\NormalTok{\}}
\NormalTok{xx}\OtherTok{\textless{}{-}}\FunctionTok{factor}\NormalTok{(xxx,}\AttributeTok{levels=}\FunctionTok{c}\NormalTok{(}\StringTok{"bajo"}\NormalTok{,}\StringTok{"medio"}\NormalTok{,}\StringTok{"alto"}\NormalTok{),}\AttributeTok{labels=}\FunctionTok{c}\NormalTok{(}\StringTok{"B"}\NormalTok{,}\StringTok{"M"}\NormalTok{,}\StringTok{"A"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{generuxe1-el-siguiente-data.frame}{%
\subsubsection{\texorpdfstring{Generá el siguiente
\texttt{data.frame()}}{Generá el siguiente data.frame()}}\label{generuxe1-el-siguiente-data.frame}}

Para ello usá el vector \texttt{xx} que obtuviste en la parte anterior.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data}\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(xx)}
\end{Highlighting}
\end{Shaded}

\hypertarget{parte-2-listas}{%
\subsection{Parte 2: Listas}\label{parte-2-listas}}

\hypertarget{generuxe1-una-lista-que-se-llame-lista_t1-que-contenga}{%
\subsubsection{\texorpdfstring{Generá una lista que se llame
\texttt{lista\_t1} que
contenga:}{Generá una lista que se llame lista\_t1 que contenga:}}\label{generuxe1-una-lista-que-se-llame-lista_t1-que-contenga}}

\begin{itemize}
\tightlist
\item
  Un vector numérico de longitud 4 (\texttt{h}).
\item
  Una matriz de dimensión 4*3 (\texttt{u}).
\item
  La palabra ``chau'' (\texttt{palabra}).
\item
  Una secuencia diaria de fechas (clase Date) desde 2021/01/01 hasta
  2021/12/30 (\texttt{fecha}).
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{h }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{)}
\NormalTok{u }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{12}\NormalTok{, }\AttributeTok{nrow=}\DecValTok{4}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{3}\NormalTok{)}
\NormalTok{palabra }\OtherTok{\textless{}{-}} \StringTok{"chau"}
\NormalTok{s}\OtherTok{\textless{}{-}}\FunctionTok{as.Date}\NormalTok{(}\StringTok{"2021{-}01{-}01"}\NormalTok{)}
\NormalTok{e}\OtherTok{\textless{}{-}}\FunctionTok{as.Date}\NormalTok{(}\StringTok{"2021{-}12{-}30"}\NormalTok{)}
\NormalTok{fecha }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\AttributeTok{from=}\NormalTok{s, }\AttributeTok{to=}\NormalTok{e, }\AttributeTok{by=}\DecValTok{1}\NormalTok{)}
\NormalTok{lista\_t1 }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(h, u, palabra, fecha)}
\end{Highlighting}
\end{Shaded}

\hypertarget{cuuxe1l-es-el-tercer-elemento-de-la-primera-fila-de-la-matriz-u-quuxe9-columna-lo-contiene}{%
\subsubsection{\texorpdfstring{¿Cuál es el tercer elemento de la primera
fila de la matriz \texttt{u}? ¿Qué columna lo
contiene?}{¿Cuál es el tercer elemento de la primera fila de la matriz u? ¿Qué columna lo contiene?}}\label{cuuxe1l-es-el-tercer-elemento-de-la-primera-fila-de-la-matriz-u-quuxe9-columna-lo-contiene}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lista\_t1[[}\DecValTok{2}\NormalTok{]][}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

El tercer elemento de la matriz u es el número 3 y al haber completado
la matriz de 4 filas, por columnas, el tercer elemento, es decir, el
número 3, pertenece a la columna 1 de la matriz u.

\hypertarget{cuuxe1l-es-la-diferencia-entre-hacer-lista_t12---0-y-lista_t12---0}{%
\subsubsection{\texorpdfstring{¿Cuál es la diferencia entre hacer
\texttt{lista\_t1{[}{[}2{]}{]}{[}{]}\ \textless{}-\ 0} y
\texttt{lista\_t1{[}{[}2{]}{]}\ \textless{}-\ 0}?}{¿Cuál es la diferencia entre hacer lista\_t1{[}{[}2{]}{]}{[}{]} \textless- 0 y lista\_t1{[}{[}2{]}{]} \textless- 0?}}\label{cuuxe1l-es-la-diferencia-entre-hacer-lista_t12---0-y-lista_t12---0}}

lista\_t1{[}{[}2{]}{]}{[}{]} devuelve el segundo objeto de la lista en
su totalidad, en este caso, la matriz u de dimensión 4x3 en su
totalidad. Al asignarle el número cero, sustituye los elementos de la
matriz por ceros, generando la matriz nula. La segunda alternativa
también devuelve en su totalidad el segundo elemento de la lista (la
matriz u), pero al asignarle el valor cero, no retorna la matriz nula,
sino el número cero.

\hypertarget{iteraciuxf3n}{%
\subsubsection{Iteración}\label{iteraciuxf3n}}

Iterá sobre la el objeto \texttt{lista\_t1} y obtené la clase de cada
elemento teniendo el cuenta que si la longitud de la clase del elemento
es mayor a uno nos quedamos con el último elemento. Es decir, si
\texttt{class(x)} es igual a \texttt{c("matrix",\ "array")} el resultado
debería ser ``array''. A su vez retorná el resultado como clase
\texttt{list} y como \texttt{character}.

\textbf{Pista}: Revisá la familia de funciones \texttt{apply}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{aux}\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{nrow=}\DecValTok{4}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{2}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(lista\_t1)) \{}
\NormalTok{  aux[i,]}\OtherTok{\textless{}{-}}\FunctionTok{class}\NormalTok{(lista\_t1[[i]])}
 
\NormalTok{\}}
\NormalTok{ clases }\OtherTok{\textless{}{-}} \FunctionTok{print}\NormalTok{(aux[,}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "numeric"   "array"     "character" "Date"
\end{verbatim}

\hypertarget{iteraciuxf3n-2}{%
\subsubsection{Iteración (2)}\label{iteraciuxf3n-2}}

Utilizando las últimas 10 observaciones de el elemento ``fecha'' del
objeto ``lista\_t1'' escriba para cada fecha ``La fecha en este momento
es \ldots.'' donde ``\ldots{}'' debe contener la fecha para valor de
lista\$fecha. Ejemplo: ``La fecha en este momento es `2021-04-28'\,''.
Hacelo de al menos 2 formas y que una de ellas sea utilizando un
\textbf{for}. \textbf{Obs}: En este ejercicio \textbf{NO} imprimas los
resultados.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fechas}\OtherTok{\textless{}{-}}\FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{10}\NormalTok{)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in}\NormalTok{ (}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]])}\SpecialCharTok{{-}}\DecValTok{9}\NormalTok{)}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]])) \{}
\NormalTok{  fechas[i] }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(}\StringTok{"La fecha en este momento es"}\NormalTok{, lista\_t1[[}\DecValTok{4}\NormalTok{]][i], }\AttributeTok{sep =} \StringTok{" "}\NormalTok{)}
\NormalTok{\}}
\FunctionTok{print}\NormalTok{(fechas)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{9}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}21"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{8}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}22"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{7}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}23"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{6}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}24"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}25"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{4}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}26"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{3}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}27"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}28"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}29"}
\NormalTok{lista\_t1[[}\DecValTok{4}\NormalTok{]][}\FunctionTok{length}\NormalTok{(lista\_t1[[}\DecValTok{4}\NormalTok{]]}\SpecialCharTok{{-}}\DecValTok{0}\NormalTok{)] }\OtherTok{\textless{}{-}} \StringTok{"La fecha en este moemnto es 2021{-}12{-}30"}
\end{Highlighting}
\end{Shaded}

\hypertarget{parte-3-matrices}{%
\subsection{Parte 3: Matrices}\label{parte-3-matrices}}

\hypertarget{generuxe1-una-matriz-a-de-dimensiuxf3n-43-y-una-matriz-b-de-dimensiuxf3n-42-con-nuxfameros-aleatorios-usando-alguna-funciuxf3n-predefinda-en-r.}{%
\subsubsection{\texorpdfstring{Generá una matriz \(A\) de dimensión
\(4*3\) y una matriz \(B\) de dimensión \(4*2\) con números aleatorios
usando alguna función predefinda en
R.}{Generá una matriz A de dimensión 4*3 y una matriz B de dimensión 4*2 con números aleatorios usando alguna función predefinda en R.}}\label{generuxe1-una-matriz-a-de-dimensiuxf3n-43-y-una-matriz-b-de-dimensiuxf3n-42-con-nuxfameros-aleatorios-usando-alguna-funciuxf3n-predefinda-en-r.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos1}\OtherTok{\textless{}{-}}\FunctionTok{runif}\NormalTok{(}\DecValTok{12}\NormalTok{, }\AttributeTok{min=}\DecValTok{0}\NormalTok{, }\AttributeTok{max=}\DecValTok{1}\NormalTok{)}
\NormalTok{datos2}\OtherTok{\textless{}{-}}\FunctionTok{runif}\NormalTok{(}\DecValTok{8}\NormalTok{, }\AttributeTok{min=}\DecValTok{0}\NormalTok{, }\AttributeTok{max=}\DecValTok{1}\NormalTok{)}
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(datos1, }\AttributeTok{nrow=}\DecValTok{4}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{3}\NormalTok{)}
\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(datos2, }\AttributeTok{nrow=}\DecValTok{4}\NormalTok{, }\AttributeTok{ncol=}\DecValTok{2}\NormalTok{)}
\FunctionTok{print}\NormalTok{(A)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           [,1]      [,2]      [,3]
## [1,] 0.9789930 0.4085161 0.9732627
## [2,] 0.9695070 0.6351302 0.9261024
## [3,] 0.1675513 0.4957441 0.7827110
## [4,] 0.8017380 0.9849971 0.7452766
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            [,1]      [,2]
## [1,] 0.58106942 0.3477855
## [2,] 0.02695959 0.4759883
## [3,] 0.18547340 0.6933982
## [4,] 0.16209157 0.4746001
\end{verbatim}

\hypertarget{calculuxe1-el-producto-elemento-a-elemento-de-la-primera-columna-de-la-matriz-a-por-la-uxfaltima-columna-de-la-matriz-b.}{%
\subsubsection{\texorpdfstring{Calculá el producto elemento a elemento
de la primera columna de la matriz \(A\) por la última columna de la
matriz
\(B\).}{Calculá el producto elemento a elemento de la primera columna de la matriz A por la última columna de la matriz B.}}\label{calculuxe1-el-producto-elemento-a-elemento-de-la-primera-columna-de-la-matriz-a-por-la-uxfaltima-columna-de-la-matriz-b.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A[,}\DecValTok{1}\NormalTok{]}\SpecialCharTok{*}\NormalTok{B[,}\DecValTok{2}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3404796 0.4614740 0.1161798 0.3805050
\end{verbatim}

\hypertarget{calculuxe1-el-producto-matricial-entre-d-atb.-luego-seleccionuxe1-los-elementos-de-la-primer-y-tercera-fila-de-la-segunda-columna-en-un-paso.}{%
\subsubsection{\texorpdfstring{Calculá el producto matricial entre
\(D = A^TB\). Luego seleccioná los elementos de la primer y tercera fila
de la segunda columna (en un
paso).}{Calculá el producto matricial entre D = A\^{}TB. Luego seleccioná los elementos de la primer y tercera fila de la segunda columna (en un paso).}}\label{calculuxe1-el-producto-matricial-entre-d-atb.-luego-seleccionuxe1-los-elementos-de-la-primer-y-tercera-fila-de-la-segunda-columna-en-un-paso.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{D}\OtherTok{\textless{}{-}}\FunctionTok{t}\NormalTok{(A)}\SpecialCharTok{\%*\%}\NormalTok{B}
\FunctionTok{print}\NormalTok{(D)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           [,1]     [,2]
## [1,] 0.7560317 1.298638
## [2,] 0.5061061 1.255618
## [3,] 0.8564757 1.675739
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{c}\NormalTok{(D[}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{], D[}\DecValTok{3}\NormalTok{,}\DecValTok{2}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.298638 1.675739
\end{verbatim}

\hypertarget{usuxe1-las-matrices-a-y-b-de-forma-tal-de-lograr-una-matriz-c-de-dimensiuxf3n-45.-con-la-funciuxf3n-attributes-inspeccionuxe1-los-atributos-de-c.-posteriormente-renombruxe1-filas-y-columnas-como-fila_1-fila_2columna_1-columna_2-vuelvuxe9-a-inspeccionar-los-atributos.-finalmente-generalizuxe1-y-escribuxed-una-funciuxf3n-que-reciba-como-argumento-una-matriz-y-devuelva-como-resultado-la-misma-matriz-con-columnas-y-filas-con-nombres.}{%
\subsubsection{\texorpdfstring{Usá las matrices \(A\) y \(B\) de forma
tal de lograr una matriz \(C\) de dimensión \(4*5\). Con la función
\texttt{attributes} inspeccioná los atributos de C. Posteriormente
renombrá filas y columnas como ``fila\_1'',
``fila\_2''\ldots{}``columna\_1'', ``columna\_2'', vuelvé a inspeccionar
los atributos. Finalmente, generalizá y escribí una función que reciba
como argumento una matriz y devuelva como resultado la misma matriz con
columnas y filas con
nombres.}{Usá las matrices A y B de forma tal de lograr una matriz C de dimensión 4*5. Con la función attributes inspeccioná los atributos de C. Posteriormente renombrá filas y columnas como ``fila\_1'', ``fila\_2''\ldots``columna\_1'', ``columna\_2'', vuelvé a inspeccionar los atributos. Finalmente, generalizá y escribí una función que reciba como argumento una matriz y devuelva como resultado la misma matriz con columnas y filas con nombres.}}\label{usuxe1-las-matrices-a-y-b-de-forma-tal-de-lograr-una-matriz-c-de-dimensiuxf3n-45.-con-la-funciuxf3n-attributes-inspeccionuxe1-los-atributos-de-c.-posteriormente-renombruxe1-filas-y-columnas-como-fila_1-fila_2columna_1-columna_2-vuelvuxe9-a-inspeccionar-los-atributos.-finalmente-generalizuxe1-y-escribuxed-una-funciuxf3n-que-reciba-como-argumento-una-matriz-y-devuelva-como-resultado-la-misma-matriz-con-columnas-y-filas-con-nombres.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{C}\OtherTok{\textless{}{-}}\FunctionTok{cbind}\NormalTok{(A,B)}
\FunctionTok{attributes}\NormalTok{(C)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $dim
## [1] 4 5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dimnames}\NormalTok{(C)}\OtherTok{\textless{}{-}}\FunctionTok{list}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"fila\_1"}\NormalTok{, }\StringTok{"fila\_2"}\NormalTok{, }\StringTok{"fila\_3"}\NormalTok{, }\StringTok{"fila\_4"}\NormalTok{), }\FunctionTok{c}\NormalTok{(}\StringTok{"columna\_1"}\NormalTok{, }\StringTok{"columna\_2"}\NormalTok{, }\StringTok{"columna\_3"}\NormalTok{, }\StringTok{"columna\_4"}\NormalTok{, }\StringTok{"columna\_5"}\NormalTok{))}
\FunctionTok{print}\NormalTok{(C)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        columna_1 columna_2 columna_3  columna_4 columna_5
## fila_1 0.9789930 0.4085161 0.9732627 0.58106942 0.3477855
## fila_2 0.9695070 0.6351302 0.9261024 0.02695959 0.4759883
## fila_3 0.1675513 0.4957441 0.7827110 0.18547340 0.6933982
## fila_4 0.8017380 0.9849971 0.7452766 0.16209157 0.4746001
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attributes}\NormalTok{(C)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $dim
## [1] 4 5
## 
## $dimnames
## $dimnames[[1]]
## [1] "fila_1" "fila_2" "fila_3" "fila_4"
## 
## $dimnames[[2]]
## [1] "columna_1" "columna_2" "columna_3" "columna_4" "columna_5"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{renombrar }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{   filas}\OtherTok{\textless{}{-}}\FunctionTok{factor}\NormalTok{()}
\NormalTok{  columnas}\OtherTok{\textless{}{-}}\FunctionTok{factor}\NormalTok{()}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{dim}\NormalTok{(x)[}\DecValTok{1}\NormalTok{]) \{}
\NormalTok{    filas}\OtherTok{\textless{}{-}}\FunctionTok{cbind}\NormalTok{(filas, }\FunctionTok{paste}\NormalTok{(}\StringTok{"fila"}\NormalTok{,i, }\AttributeTok{sep=}\StringTok{"\_"}\NormalTok{))}
\NormalTok{  \}}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{dim}\NormalTok{(x)[}\DecValTok{2}\NormalTok{]) \{}
\NormalTok{    columnas}\OtherTok{\textless{}{-}}\FunctionTok{cbind}\NormalTok{(columnas, }\FunctionTok{paste}\NormalTok{(}\StringTok{"columna"}\NormalTok{,i, }\AttributeTok{sep=}\StringTok{"\_"}\NormalTok{))}
\NormalTok{  \}}
    \FunctionTok{dimnames}\NormalTok{(x)}\OtherTok{\textless{}{-}}\FunctionTok{list}\NormalTok{(filas, columnas)}

\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{puntos-extra-genelarizuxe1-la-funciuxf3n-para-que-funcione-con-arrays-de-forma-que-renombre-filas-columnas-y-matrices.}{%
\subsubsection{Puntos Extra: genelarizá la función para que funcione con
arrays de forma que renombre filas, columnas y
matrices.}\label{puntos-extra-genelarizuxe1-la-funciuxf3n-para-que-funcione-con-arrays-de-forma-que-renombre-filas-columnas-y-matrices.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{renombrar\_array }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
  \FunctionTok{lapply}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{, }\ControlFlowTok{function}\NormalTok{(idx) \{}
\FunctionTok{dimnames}\NormalTok{(x)[[idx]] }\OtherTok{\textless{}\textless{}{-}} \FunctionTok{paste0}\NormalTok{(}\FunctionTok{ifelse}\NormalTok{(idx}\SpecialCharTok{==}\DecValTok{1}\NormalTok{, }\StringTok{"fila\_"}\NormalTok{, }\FunctionTok{ifelse}\NormalTok{(idx}\SpecialCharTok{==}\DecValTok{2}\NormalTok{, }\StringTok{"columna\_"}\NormalTok{, }\StringTok{"matriz\_"}\NormalTok{)), }\DecValTok{1}\SpecialCharTok{:}\FunctionTok{dim}\NormalTok{(x)[[idx]])}
\NormalTok{\})}
\FunctionTok{return}\NormalTok{(x)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{ejercicio-2}{%
\section{Ejercicio 2}\label{ejercicio-2}}

\hypertarget{parte-1-ifelse}{%
\subsection{\texorpdfstring{Parte 1:
\texttt{ifelse()}}{Parte 1: ifelse()}}\label{parte-1-ifelse}}

\hypertarget{quuxe9-hace-la-funciuxf3n-ifelse-del-paquete-base-de-r}{%
\subsubsection{\texorpdfstring{¿Qué hace la función \texttt{ifelse()}
del paquete \texttt{base} de
R?}{¿Qué hace la función ifelse() del paquete base de R?}}\label{quuxe9-hace-la-funciuxf3n-ifelse-del-paquete-base-de-r}}

La función ifelse funciona como un condicional booleano. Es decir
plantea una condición que ejecuta cierta orden si se cumple. Si no se
cumple `else' ejecuta otra sentencia dada. La estructura de la función
es: una expresión booleana seguida de la sentencia a ejecutar si el
booleano se cumple y por último, la sentencia a ejecutar si el booleano
no se cumple.

\hypertarget{dado-el-vector-x-tal-que-x---c8-6-22-1-0--2--45-utilizando-la-funciuxf3n-ifelse-del-paquete-base-reemplazuxe1-todos-los-elementos-mayores-estrictos-a-0-por-1-y-todos-los-elementos-menores-o-iguales-a-0-por-0.}{%
\subsubsection{\texorpdfstring{Dado el vector \(x\) tal que:
\texttt{x\ \textless{}-\ c(8,\ 6,\ 22,\ 1,\ 0,\ -2,\ -45)}, utilizando
la función \texttt{ifelse()} del paquete \texttt{base}, reemplazá todos
los elementos mayores estrictos a \texttt{0} por \texttt{1}, y todos los
elementos menores o iguales a \texttt{0} por
\texttt{0}.}{Dado el vector x tal que: x \textless- c(8, 6, 22, 1, 0, -2, -45), utilizando la función ifelse() del paquete base, reemplazá todos los elementos mayores estrictos a 0 por 1, y todos los elementos menores o iguales a 0 por 0.}}\label{dado-el-vector-x-tal-que-x---c8-6-22-1-0--2--45-utilizando-la-funciuxf3n-ifelse-del-paquete-base-reemplazuxe1-todos-los-elementos-mayores-estrictos-a-0-por-1-y-todos-los-elementos-menores-o-iguales-a-0-por-0.}}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(x)) \{}
\NormalTok{  x[i] }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(x[i]}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors

## Warning in Ops.factor(x[i], 0): '>' not meaningful for factors
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA>
## [16] <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA>
## 15 Levels: A alto ALTO B bajo BAJO C GOL GUAU medio MEDIO muy alto ... QUE LOCO
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ifelse}\NormalTok{(x}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in Ops.factor(x, 0): '>' not meaningful for factors
\end{verbatim}

\begin{verbatim}
##  [1] NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA
\end{verbatim}

\hypertarget{por-quuxe9-no-fuuxe9-necesario-usar-un-loop}{%
\subsubsection{¿Por qué no fué necesario usar un loop
?}\label{por-quuxe9-no-fuuxe9-necesario-usar-un-loop}}

Porque es una única condición a aplicarse a todos los elementos del
vector x. Además, la función ifelse permite no solo modificar cuando se
cumple la condición, sino tambien cuando no se cumple.

\hypertarget{parte-2-while-loops}{%
\subsection{\texorpdfstring{Parte 2: \texttt{while()}
loops}{Parte 2: while() loops}}\label{parte-2-while-loops}}

\hypertarget{quuxe9-es-un-while-loop-y-cuxf3mo-es-la-estructura-para-generar-uno-en-r-en-quuxe9-se-diferencia-de-un-for-loop}{%
\subsubsection{¿Qué es un while loop y cómo es la estructura para
generar uno en R? ¿En qué se diferencia de un for
loop?}\label{quuxe9-es-un-while-loop-y-cuxf3mo-es-la-estructura-para-generar-uno-en-r-en-quuxe9-se-diferencia-de-un-for-loop}}

La función while se diferencia del for en que no es necesario hacer un
recorrido iterativo estricto, sino que permite que la iteración se lleve
adelante sólo si se cumple una condición dada.

\hypertarget{dada-la-estructura-siguiente-cuuxe1l-es-el-valor-del-objeto-suma-responda-sin-realizar-el-cuxe1lculo-en-r.}{%
\subsubsection{\texorpdfstring{Dada la estructura siguiente, ¿Cuál es el
valor del objeto \texttt{suma}? Responda sin realizar el cálculo en
\texttt{R}.}{Dada la estructura siguiente, ¿Cuál es el valor del objeto suma? Responda sin realizar el cálculo en R.}}\label{dada-la-estructura-siguiente-cuuxe1l-es-el-valor-del-objeto-suma-responda-sin-realizar-el-cuxe1lculo-en-r.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{)}
\NormalTok{suma }\OtherTok{\textless{}{-}} \DecValTok{0}
\NormalTok{i }\OtherTok{\textless{}{-}} \DecValTok{1}
\ControlFlowTok{while}\NormalTok{(i }\SpecialCharTok{\textless{}} \DecValTok{6}\NormalTok{)\{}
\NormalTok{ suma }\OtherTok{=}\NormalTok{ suma }\SpecialCharTok{+}\NormalTok{ x[i]      }
\NormalTok{ i }\OtherTok{\textless{}{-}}\NormalTok{ i }\SpecialCharTok{+} \DecValTok{1}     
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

El razonamiento (sin previo cálculo en R) es el siguiente: dado x,
defino una variable suma en cero. Luego inicializo un contador i a
partir de 1. La interación comienza en i=1 y se detiene cuando i toma
valores a partir de 6. Así, iniciando en 1, se realiza la iteración
sumando la variable suma que originalmente vale cero por el primer
elemeno de x, es decir 0+1. Luego le ordeno al contador que tome el
valor 2 (i=1+1). Como el contador toma el valor 2 vuelvo a iterar
sumando la variable suma que vale 1 por el segundo elemento de x, 2, lo
que da 3. Luego el contador parte de i=2+1=3 y como es menor que 6
nuevamente sumo el tercer elemento de x, lo que resulta, 3+3 =6. El
contador vale 4 pero no hay más elementos en x para sumar. Así el valor
de suma dará un elemento en blanco porque no se logró completar con
éxito el algoritmo.

\hypertarget{modificuxe1-la-estructura-anterior-para-que-suma-valga-0-si-el-vector-tiene-largo-menor-a-5-o-que-sume-los-primeros-5-elementos-si-el-vector-tiene-largo-mayor-a-5.-a-partir-de-ella-generuxe1-una-fuciuxf3n-que-se-llame-sumar_si-y-verificuxe1-que-funcione-utilizando-los-vectores-y---c13-z---c115.}{%
\subsubsection{\texorpdfstring{Modificá la estructura anterior para que
\texttt{suma} valga 0 si el vector tiene largo menor a 5, o que sume los
primeros 5 elementos si el vector tiene largo mayor a 5. A partir de
ella generá una fución que se llame \texttt{sumar\_si} y verificá que
funcione utilizando los vectores \texttt{y\ \textless{}-\ c(1:3)},
\texttt{z\ \textless{}-\ c(1:15)}.}{Modificá la estructura anterior para que suma valga 0 si el vector tiene largo menor a 5, o que sume los primeros 5 elementos si el vector tiene largo mayor a 5. A partir de ella generá una fución que se llame sumar\_si y verificá que funcione utilizando los vectores y \textless- c(1:3), z \textless- c(1:15).}}\label{modificuxe1-la-estructura-anterior-para-que-suma-valga-0-si-el-vector-tiene-largo-menor-a-5-o-que-sume-los-primeros-5-elementos-si-el-vector-tiene-largo-mayor-a-5.-a-partir-de-ella-generuxe1-una-fuciuxf3n-que-se-llame-sumar_si-y-verificuxe1-que-funcione-utilizando-los-vectores-y---c13-z---c115.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(x)}\SpecialCharTok{\textgreater{}=}\DecValTok{5}\NormalTok{) \{ }
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) \{ }
\NormalTok{      suma }\OtherTok{=}\NormalTok{ suma }\SpecialCharTok{+}\NormalTok{ x[i]}
\NormalTok{      \}}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{  suma}\OtherTok{=}\DecValTok{0}
\NormalTok{\}}

\NormalTok{sumar\_si }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(v) \{}
\NormalTok{  suma}\OtherTok{=}\DecValTok{0}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(v)}\SpecialCharTok{\textgreater{}=}\DecValTok{5}\NormalTok{) \{ }
    \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\DecValTok{5}\NormalTok{) \{ }
\NormalTok{      suma }\OtherTok{=}\NormalTok{ suma }\SpecialCharTok{+}\NormalTok{ v[i]}
\NormalTok{      \}}
\NormalTok{  \}}
  \FunctionTok{print}\NormalTok{(suma)}
\NormalTok{\}}

\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{)}
\NormalTok{z }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{15}\NormalTok{)}
\FunctionTok{sumar\_si}\NormalTok{(y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sumar\_si}\NormalTok{(z)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15
\end{verbatim}

\hypertarget{generuxe1-una-estructura-que-multiplique-los-nuxfameros-naturales-empezando-por-el-1-hasta-que-dicha-multiplicaciuxf3n-supere-el-valor-10000.-cuuxe1nto-vale-dicha-productoria}{%
\subsubsection{\texorpdfstring{Generá una estructura que multiplique los
números naturales (empezando por el 1) hasta que dicha multiplicación
supere el valor \texttt{10000}. Cuánto vale dicha
productoria?}{Generá una estructura que multiplique los números naturales (empezando por el 1) hasta que dicha multiplicación supere el valor 10000. Cuánto vale dicha productoria?}}\label{generuxe1-una-estructura-que-multiplique-los-nuxfameros-naturales-empezando-por-el-1-hasta-que-dicha-multiplicaciuxf3n-supere-el-valor-10000.-cuuxe1nto-vale-dicha-productoria}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{producto }\OtherTok{\textless{}{-}} \DecValTok{1}
\NormalTok{i }\OtherTok{\textless{}{-}} \DecValTok{1}
\ControlFlowTok{while}\NormalTok{ (producto }\SpecialCharTok{\textless{}=} \DecValTok{10000}\NormalTok{) \{}
\NormalTok{  producto }\OtherTok{=}\NormalTok{ producto}\SpecialCharTok{*}\NormalTok{(i}\SpecialCharTok{+}\DecValTok{1}\NormalTok{)}
\NormalTok{  i}\OtherTok{=}\NormalTok{i}\SpecialCharTok{+}\DecValTok{1}
  \FunctionTok{print}\NormalTok{(producto)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2
## [1] 6
## [1] 24
## [1] 120
## [1] 720
## [1] 5040
## [1] 40320
\end{verbatim}

El resultado de la productoria es de 40320: el primer resultado luego de
superados los 10000. Como 40320 no es inferior a 10000 el algoritmo se
detiene y se dejan de realizar productos.

\hypertarget{parte-3-ordenar}{%
\subsection{Parte 3: Ordenar}\label{parte-3-ordenar}}

\hypertarget{generuxe1-una-funciuxf3n-ordenar_xque-para-cualquier-vector-numuxe9rico-ordene-sus-elementos-de-menor-a-mayor.-por-ejemplo}{%
\subsubsection{\texorpdfstring{Generá una función
\texttt{ordenar\_x()}que para cualquier vector numérico, ordene sus
elementos de menor a mayor. Por
ejemplo:}{Generá una función ordenar\_x()que para cualquier vector numérico, ordene sus elementos de menor a mayor. Por ejemplo:}}\label{generuxe1-una-funciuxf3n-ordenar_xque-para-cualquier-vector-numuxe9rico-ordene-sus-elementos-de-menor-a-mayor.-por-ejemplo}}

Sea \texttt{x\ \textless{}-\ c(3,4,5,-2,1)}, \texttt{ordenar\_x(x)}
devuelve \texttt{c(-2,1,3,4,5)}.

Para controlar, generá dos vectores numéricos cualquiera y pasalos como
argumentos en \texttt{ordenar\_x()}.

Observación: Si usa la función \texttt{base::order()} entonces debe
escribir 2 funciones. Una usando \texttt{base::order()} y otra sin
usarla.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ordenar\_x}\OtherTok{\textless{}{-}}\ControlFlowTok{function}\NormalTok{(v)\{}
\NormalTok{  a}\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{()}
\NormalTok{  j}\OtherTok{\textless{}{-}}\DecValTok{1}
\ControlFlowTok{while}\NormalTok{ (j }\SpecialCharTok{\textless{}} \FunctionTok{length}\NormalTok{(v))\{}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{(}\FunctionTok{length}\NormalTok{(v)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))\{}
  \ControlFlowTok{if}\NormalTok{ (v[i]}\SpecialCharTok{\textgreater{}}\NormalTok{v[i}\SpecialCharTok{+}\DecValTok{1}\NormalTok{])\{}
\NormalTok{    a[i]}\OtherTok{\textless{}{-}}\NormalTok{v[i]}
\NormalTok{    v[i]}\OtherTok{\textless{}{-}}\NormalTok{v[i}\SpecialCharTok{+}\DecValTok{1}\NormalTok{]}
\NormalTok{    v[i}\SpecialCharTok{+}\DecValTok{1}\NormalTok{]}\OtherTok{\textless{}{-}}\NormalTok{a[i]  }\CommentTok{\#Cambio de lugar los elementos del vector ordenandolos de menor a mayor}
\NormalTok{    \}}
\NormalTok{  \}}
\NormalTok{  j}\OtherTok{\textless{}{-}}\NormalTok{j}\SpecialCharTok{+}\DecValTok{1}\NormalTok{\}  }
  \FunctionTok{print}\NormalTok{(v)}
\NormalTok{\}}
\NormalTok{x }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{5}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{2}\NormalTok{,}\DecValTok{1}\NormalTok{)}
\FunctionTok{ordenar\_x}\NormalTok{(x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -2  1  3  4  5
\end{verbatim}

\hypertarget{quuxe9-devuelve-orderorderx}{%
\subsubsection{\texorpdfstring{¿Qué devuelve
\texttt{order(order(x))}?}{¿Qué devuelve order(order(x))?}}\label{quuxe9-devuelve-orderorderx}}

La función order devuelve en las posiciones de los elementos del vector
x, estos elementos ordenados de menor a mayor. Esta función a su vez
devuelve un nuevo vector con las posiciones. Al aplicar nuevamente la
función order a la ya aplicada función order del vector x, se repite la
lógica: del nuevo vector de posiciones de x devuelve otro vector con las
posiciones de los elementos ordenados de menor a mayor del vecto dado.
order(x) devuelve un vector de posiciones de los elementos de x
ordenados de menor a mayor. order(order(x)) develve un vector de
posiciones de los elementos de (order(x)) ordenados de menor a mayor.

\hypertarget{ejercicios-extra}{%
\section{Ejercicios Extra}\label{ejercicios-extra}}

Esta parte es opcional pero de hacerla tendrán puntos extra.

\hypertarget{extra-1}{%
\subsection{Extra 1}\label{extra-1}}

\hypertarget{quuxe9-funciuxf3n-del-paquete-base-es-la-que-tiene-mayor-cantidad-de-argumentos}{%
\subsubsection{¿Qué función del paquete base es la que tiene mayor
cantidad de
argumentos?}\label{quuxe9-funciuxf3n-del-paquete-base-es-la-que-tiene-mayor-cantidad-de-argumentos}}

\textbf{Pistas}: Posible solución:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{-1}
\tightlist
\item
  Argumentos = \texttt{formals()}
\item
  Para comenzar use \texttt{ls("package:base")} y luego revise la
  función \texttt{get()} y \texttt{mget()} (use esta última, necesita
  modificar un parámetro ó formals).
\item
  Revise la funcion Filter
\item
  Itere
\item
  Obtenga el índice de valor máximo
\end{enumerate}

\hypertarget{extra-2}{%
\subsection{Extra 2}\label{extra-2}}

Dado el siguiente vector:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{valores }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\end{Highlighting}
\end{Shaded}

\hypertarget{obtenuxe9-la-suma-acumulada-es-decir-1-3-6-10de-dos-formas-y-que-una-de-ellas-sea-utilizando-la-funciuxf3n-reduce.}{%
\subsubsection{\texorpdfstring{Obtené la suma acumulada, es decir 1, 3,
6, 10\ldots de dos formas y que una de ellas sea utilizando la función
\texttt{Reduce}.}{Obtené la suma acumulada, es decir 1, 3, 6, 10\ldots de dos formas y que una de ellas sea utilizando la función Reduce.}}\label{obtenuxe9-la-suma-acumulada-es-decir-1-3-6-10de-dos-formas-y-que-una-de-ellas-sea-utilizando-la-funciuxf3n-reduce.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{valores }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\CommentTok{\# Forma 1}
\NormalTok{suma\_acum}\OtherTok{\textless{}{-}}\DecValTok{1}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{2}\SpecialCharTok{:}\DecValTok{20}\NormalTok{) \{}
\NormalTok{  suma\_acum }\OtherTok{=}\NormalTok{ suma\_acum }\SpecialCharTok{+}\NormalTok{ valores[i]}
  \FunctionTok{print}\NormalTok{(suma\_acum)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
## [1] 6
## [1] 10
## [1] 15
## [1] 21
## [1] 28
## [1] 36
## [1] 45
## [1] 55
## [1] 66
## [1] 78
## [1] 91
## [1] 105
## [1] 120
## [1] 136
## [1] 153
## [1] 171
## [1] 190
## [1] 210
\end{verbatim}

La suma acumulada es 210

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{valores }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\CommentTok{\# Forma 2}
\NormalTok{suma\_acum2 }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(x)}\SpecialCharTok{==}\DecValTok{1}\NormalTok{) \{ }
\NormalTok{    y}\OtherTok{\textless{}{-}}\NormalTok{x[}\DecValTok{1}\NormalTok{]   \}}
  \ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{    y }\OtherTok{\textless{}{-}}\NormalTok{ x[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \FunctionTok{suma\_acum2}\NormalTok{(x[}\DecValTok{2}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(x)]) }
\NormalTok{  \}}
  \FunctionTok{print}\NormalTok{(y)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Nuevamente se verifica que el resultado de la suma acumulada es de 210.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{valores }\OtherTok{\textless{}{-}} \DecValTok{1}\SpecialCharTok{:}\DecValTok{20}
\CommentTok{\# Forma 1}
\FunctionTok{Reduce}\NormalTok{(}\ControlFlowTok{function}\NormalTok{(x,y) x }\SpecialCharTok{+}\NormalTok{ y,  valores)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 210
\end{verbatim}

Nuevamente, el resultado es 210

Dados los siguientes data.frame

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{a }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{a1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }
               \AttributeTok{b1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,}
               \AttributeTok{c1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,}
               \AttributeTok{key =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}
\NormalTok{b }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{d1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }
               \AttributeTok{e1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,}
               \AttributeTok{f1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }
               \AttributeTok{key =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}
\NormalTok{c }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{g1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }
               \AttributeTok{h1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,}
               \AttributeTok{i1 =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{,}
               \AttributeTok{key =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Uní en un solo data.frame usando la función \texttt{Reduce()}.
\textbf{Pista}: Revisá la ayuda de la función \texttt{merge()} y buscá
en material adicional si es necesario que es un join/merge.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{d }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(a, b, }\AttributeTok{by.x=}\NormalTok{ a}\SpecialCharTok{$}\NormalTok{key, }\AttributeTok{by.y=}\NormalTok{b}\SpecialCharTok{$}\NormalTok{key)}
\NormalTok{unificada }\OtherTok{\textless{}{-}} \FunctionTok{merge}\NormalTok{(d, c, }\AttributeTok{by.x=}\NormalTok{a}\SpecialCharTok{$}\NormalTok{key, }\AttributeTok{by.y=}\NormalTok{ c}\SpecialCharTok{$}\NormalTok{key)}
\end{Highlighting}
\end{Shaded}

\hypertarget{extra-3}{%
\subsection{Extra 3}\label{extra-3}}

\hypertarget{escribuxed-una-funciuxf3n-que-reciba-como-input-un-vector-nuxfamerico-y-devuelva-los-uxedndices-donde-un-nuxfamero-se-repite-al-menos-k-veces.-los-paruxe1metros-deben-ser-el-vector-el-nuxfamero-a-buscar-y-la-cantidad-muxednima-de-veces-que-se-debe-repetir.-si-el-nuxfamero-no-se-encuentra-retorne-un-warning-y-el-valor-null.}{%
\subsubsection{\texorpdfstring{Escribí una función que reciba como input
un vector númerico y devuelva los índices donde un número se repite al
menos k veces. Los parámetros deben ser el vector, el número a buscar y
la cantidad mínima de veces que se debe repetir. Si el número no se
encuentra, retorne un \texttt{warning} y el valor
\texttt{NULL}.}{Escribí una función que reciba como input un vector númerico y devuelva los índices donde un número se repite al menos k veces. Los parámetros deben ser el vector, el número a buscar y la cantidad mínima de veces que se debe repetir. Si el número no se encuentra, retorne un warning y el valor NULL.}}\label{escribuxed-una-funciuxf3n-que-reciba-como-input-un-vector-nuxfamerico-y-devuelva-los-uxedndices-donde-un-nuxfamero-se-repite-al-menos-k-veces.-los-paruxe1metros-deben-ser-el-vector-el-nuxfamero-a-buscar-y-la-cantidad-muxednima-de-veces-que-se-debe-repetir.-si-el-nuxfamero-no-se-encuentra-retorne-un-warning-y-el-valor-null.}}

A modo de ejemplo, pruebe con el vector
\texttt{c(3,\ 1,\ 2,\ 3,\ 3,\ 3,\ 5,\ 5,\ 3,\ 3,\ 0,\ 0,\ 9,\ 3,\ 3,\ 3)},
buscando el número 3 al menos 3 veces. Los índices que debería obtener
son 4 y 14.

\hypertarget{extra-4}{%
\subsection{Extra 4}\label{extra-4}}

Dado el siguiente \texttt{factor}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f1 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(letters)}
\end{Highlighting}
\end{Shaded}

\hypertarget{quuxe9-hace-el-siguiente-cuxf3digo-explicuxe1-las-diferencias-o-semejanzas.}{%
\subsubsection{¿Qué hace el siguiente código? Explicá las diferencias o
semejanzas.}\label{quuxe9-hace-el-siguiente-cuxf3digo-explicuxe1-las-diferencias-o-semejanzas.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(f1) }\OtherTok{\textless{}{-}} \FunctionTok{rev}\NormalTok{(}\FunctionTok{levels}\NormalTok{(f1))}
\NormalTok{f2 }\OtherTok{\textless{}{-}} \FunctionTok{rev}\NormalTok{(}\FunctionTok{factor}\NormalTok{(letters))}
\NormalTok{f3 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(letters, }\AttributeTok{levels =} \FunctionTok{rev}\NormalTok{(letters)) }
\end{Highlighting}
\end{Shaded}

levels(f1) devuelve los niveles del factor f1 en órden invertido. f2 es
igual a f1 en cuanto a devolver el orden reveso. Sin embargo, mientras
en el primer caso lo que se devielve en orden inverso son los niveles
del factor, en f2 lo que se devielve en orden inverso son los factores
propiamente dicho. Los niveles se devuelven en orden alfabético. f3 hace
un factor con las letras del abecedario, al igual que f1, pero devuelve
los niveles de los fatores en orden inverso.

\end{document}
